name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
      kafka:
        image: bitnami/kafka:latest
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
          - 9092:9092
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./atc-lite/atc-lite.sln
      - name: Build
        run: dotnet build --no-restore --configuration Release ./atc-lite/atc-lite.sln
      - name: Test
        run: dotnet test --no-build --configuration Release ./atc-lite/atc-lite.sln --logger trx --filter FullyQualifiedName~E2ETests
        env:
          E2E_JWT: ${{ secrets.E2E_JWT }}
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'
