version: '3.8'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false --kafka-addr PLAINTEXT://0.0.0.0:9092 --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9644/v1/status/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - Redis__ConnectionString=redis:6379
      - Kafka__BootstrapServers=redpanda:9092
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - redpanda
  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    environment:
      - Redis__ConnectionString=redis:6379
      - Kafka__BootstrapServers=redpanda:9092
    depends_on:
      - redis
      - redpanda
  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    environment:
      - KAFKA=redpanda:9092
      - TOPIC=aircraft.position
      - RATE_HZ=5
      - COUNT=5
    depends_on:
      - redpanda
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://redpanda:9644/v1/status/ready"]
      interval: 10s
      timeout: 5s
      retries: 10
